<?php

return [
    'brand' => [
        'name' => 'Sentriq',
        'full_name' => 'Sentriq by Xytriq',
        'slogan' => 'Protegemos tu espacio con soluciones hechas para ti.',
    ],

    'contact' => [
        'whatsapp_display' => '+52 33 2123 1570',
        'whatsapp_number' => '523321231570',
        'whatsapp_url' => 'https://wa.me/523321231570?text=Hola%20Sentriq%2C%20me%20gustar%C3%ADa%20recibir%20asesor%C3%ADa%20para%20un%20proyecto%20de%20seguridad.',
        'email' => 'soporte@sentriq.xytriq.com',
        'facebook' => 'https://www.facebook.com/sentriq.xytriq',
        'hours' => 'Lunes a sábado, de 10:00 a. m. a 8:00 p. m.',
    ],

    'coverage' => [
        'Guadalajara',
        'Zapopan',
        'Tonalá',
        'San Pedro Tlaquepaque',
        'Tlajomulco de Zúñiga',
        'Zona Metropolitana de Guadalajara',
    ],

    'services' => [
        'camaras-de-seguridad' => [
            'name' => 'Cámaras de seguridad',
            'short_name' => 'Cámaras',
            'priority' => 'principal',
            'summary' => 'Videovigilancia para saber qué sucede en tu hogar, incluso cuando estás lejos.',
            'intro' => 'Diseñamos sistemas de videovigilancia de acuerdo con los accesos, áreas vulnerables y hábitos de cada hogar. Te ayudamos a elegir entre soluciones IP, analógicas o Wi-Fi y dejamos el sistema configurado para consultarlo desde tu celular.',
            'features' => [
                'Sistemas IP, analógicos y Wi-Fi',
                'Visualización remota desde celular',
                'Visión nocturna y opciones a color',
                'Audio y detección inteligente',
                'Grabación local y respaldo adecuado',
                'Instalación ordenada y configuración completa',
            ],
            'benefits' => [
                'Supervisa accesos y áreas importantes desde cualquier lugar.',
                'Consulta grabaciones cuando necesites verificar un evento.',
                'Recibe orientación para evitar comprar equipo innecesario.',
            ],
            'brands' => ['Dahua', 'Saxxon', 'HiLook', 'Hikvision', 'EPCOM'],
            'whatsapp_message' => 'Hola Sentriq, quiero información sobre cámaras de seguridad para mi hogar.',
        ],
        'automatizacion-de-portones' => [
            'name' => 'Automatización de portones',
            'short_name' => 'Portones',
            'priority' => 'principal',
            'summary' => 'Entra y sal de casa con mayor comodidad, control y seguridad.',
            'intro' => 'Automatizamos portones corredizos, abatibles y de otros tipos después de revisar su estructura, peso, uso diario y condiciones de instalación. La selección correcta del motor es clave para conseguir un funcionamiento seguro y durable.',
            'features' => [
                'Evaluación del portón existente',
                'Motores para diferentes pesos y ciclos de uso',
                'Controles remotos y accesorios de seguridad',
                'Fotoceldas y sistemas de apertura',
                'Instalación eléctrica y mecánica ordenada',
                'Mantenimiento y diagnóstico',
            ],
            'benefits' => [
                'Evita bajar del vehículo para abrir manualmente.',
                'Controla mejor quién entra a la propiedad.',
                'Obtén un sistema dimensionado para el uso real del portón.',
            ],
            'brands' => ['SEG', 'Merik', 'FAAC', 'AccessPRO', 'ZKTeco'],
            'whatsapp_message' => 'Hola Sentriq, quiero automatizar un portón y necesito una valoración.',
        ],
        'control-de-acceso' => [
            'name' => 'Control de acceso',
            'short_name' => 'Acceso',
            'priority' => 'principal',
            'summary' => 'Decide quién puede entrar y mantén un mejor control de tus espacios.',
            'intro' => 'Implementamos controles de acceso para puertas, áreas restringidas y pequeños negocios. Integramos los dispositivos adecuados según el número de usuarios, el nivel de seguridad y la forma en que necesitas administrar las entradas.',
            'features' => [
                'Acceso mediante tarjeta, código o biometría',
                'Cerraduras y electroimanes',
                'Videoporteros e intercomunicación',
                'Registro y administración de usuarios',
                'Botones de salida y accesorios',
                'Soluciones residenciales y comerciales',
            ],
            'benefits' => [
                'Reduce la dependencia de llaves convencionales.',
                'Administra altas y bajas de usuarios con mayor facilidad.',
                'Adapta el nivel de control a cada puerta o zona.',
            ],
            'brands' => ['AccessPRO', 'Dahua', 'Hikvision', 'ZKTeco', 'Ylink'],
            'whatsapp_message' => 'Hola Sentriq, necesito asesoría para un sistema de control de acceso.',
        ],
        'alarmas' => [
            'name' => 'Alarmas',
            'short_name' => 'Alarmas',
            'priority' => 'complementario',
            'summary' => 'Detecta aperturas o movimientos y recibe alertas oportunas.',
            'intro' => 'Diseñamos sistemas de alarma considerando accesos, ventanas, áreas de paso y rutinas del inmueble. El objetivo es lograr una detección útil y fácil de operar, evitando soluciones sobredimensionadas.',
            'features' => [
                'Sensores de movimiento y apertura',
                'Sirenas y avisos de emergencia',
                'Control desde aplicación',
                'Modos de armado adaptados al inmueble',
                'Expansión con dispositivos adicionales',
                'Configuración y explicación de uso',
            ],
            'benefits' => [
                'Recibe alertas ante eventos relevantes.',
                'Protege accesos aun cuando no estás en casa.',
                'Complementa tu sistema de videovigilancia.',
            ],
            'brands' => ['Hikvision'],
            'whatsapp_message' => 'Hola Sentriq, quiero conocer opciones de alarmas para mi propiedad.',
        ],
        'cercas-electricas' => [
            'name' => 'Cercas eléctricas',
            'short_name' => 'Cercas',
            'priority' => 'complementario',
            'summary' => 'Refuerza el perímetro de tu propiedad con una instalación segura.',
            'intro' => 'Instalamos cercas eléctricas como una barrera disuasiva adicional para bardas y perímetros. Evaluamos el recorrido, la estructura y los puntos de acceso para proponer una instalación limpia, señalizada y correctamente energizada.',
            'features' => [
                'Valoración del perímetro',
                'Energizadores y respaldo adecuados',
                'Postes, aisladores y cableado',
                'Señalización preventiva',
                'Integración con alarma cuando aplica',
                'Revisión y mantenimiento',
            ],
            'benefits' => [
                'Añade una barrera disuasiva visible.',
                'Refuerza zonas perimetrales vulnerables.',
                'Recibe una instalación dimensionada y revisada.',
            ],
            'brands' => ['SEG', 'Yonusa'],
            'whatsapp_message' => 'Hola Sentriq, necesito una valoración para instalar una cerca eléctrica.',
        ],
        'acceso-vehicular' => [
            'name' => 'Acceso vehicular',
            'short_name' => 'Vehicular',
            'priority' => 'complementario',
            'summary' => 'Administra entradas y salidas de vehículos de forma ágil y controlada.',
            'intro' => 'Integramos soluciones para controlar el acceso de vehículos en residencias, condominios y empresas. La propuesta puede combinar barreras, lectores, tags y controles según el flujo esperado y la administración requerida.',
            'features' => [
                'Barreras vehiculares',
                'Lectores y tags de proximidad',
                'Controles remotos',
                'Registro y administración de accesos',
                'Sensores y accesorios de seguridad',
                'Integración con otros sistemas',
            ],
            'benefits' => [
                'Agiliza el ingreso de vehículos autorizados.',
                'Reduce accesos sin control.',
                'Escala la solución conforme crecen los usuarios.',
            ],
            'brands' => ['AccessPRO', 'Dahua', 'Hikvision', 'ZKTeco', 'Ylink'],
            'whatsapp_message' => 'Hola Sentriq, necesito una solución de acceso vehicular.',
        ],
    ],
];
