@extends('admin.layout')
@section('title', $prospect->displayName())
@section('content')
    <div class="admin-heading"><div><span>{{ \App\Models\Prospect::SOURCES[$prospect->source] }}</span><h1>{{ $prospect->displayName() }}</h1><p>{{ $prospect->name && $prospect->business ? $prospect->name.' · ' : '' }}{{ $prospect->municipality }}</p></div><div class="heading-actions">@if ($prospect->whatsappUrl())<a class="admin-button whatsapp-action" href="{{ $prospect->whatsappUrl() }}" target="_blank" rel="noopener">Abrir WhatsApp</a>@endif<a class="admin-button admin-button--secondary" href="{{ route('admin.prospects.edit', $prospect) }}">Editar ficha</a></div></div>

    @if ($duplicates->isNotEmpty())<div class="warning-panel"><strong>Posible coincidencia</strong><p>Hay {{ $duplicates->count() }} ficha(s) con el mismo teléfono o correo. Revísalas antes de decidir si corresponden a la misma persona.</p>@foreach ($duplicates as $duplicate)<a href="{{ route('admin.prospects.show', $duplicate) }}">{{ $duplicate->displayName() }}</a>@endforeach</div>@endif

    <div class="prospect-layout"><div>
        <section class="detail-card"><div class="detail-grid"><div><span>Etapa</span><strong>{{ \App\Models\Prospect::STAGES[$prospect->stage] }}</strong></div><div><span>Solicitud</span><strong>{{ \App\Models\Prospect::REQUEST_TYPES[$prospect->request_type] }}</strong></div><div><span>Servicio</span><strong>{{ config('sentriq.services.'.$prospect->service_interest.'.name', 'Por definir') }}</strong></div><div><span>Teléfono</span><strong>{{ $prospect->phone ?: '—' }}</strong></div><div><span>Correo</span><strong>{{ $prospect->email ?: '—' }}</strong></div><div><span>Siguiente seguimiento</span><strong @class(['is-overdue' => $prospect->next_follow_up_at?->isPast()])>{{ $prospect->next_follow_up_at?->format('d/m/Y H:i') ?: '—' }}</strong></div><div><span>Responsable</span><strong>{{ $prospect->assignedUser?->name ?: 'Sin asignar' }}</strong></div></div>@if ($prospect->description)<p>{{ $prospect->description }}</p>@endif</section>

        <section class="timeline"><h2>Actividad</h2>@forelse ($prospect->activities as $activity)<article><div><strong>{{ \App\Models\Prospect::ACTIVITY_TYPES[$activity->type] ?? $activity->type }}</strong><time>{{ $activity->happened_at->format('d/m/Y H:i') }}</time></div><p>{{ $activity->summary }}</p><small>{{ $activity->user?->name ?: 'Sitio web' }}@if ($activity->next_action) · Siguiente: {{ $activity->next_action }} ({{ $activity->next_action_at?->format('d/m/Y H:i') }})@endif</small></article>@empty<p class="empty-panel">Aún no hay actividad.</p>@endforelse</section>
    </div><aside>
        <form class="admin-form activity-form" method="POST" action="{{ route('admin.prospects.activities.store', $prospect) }}">@csrf<h2>Registrar actividad</h2><label><span>Tipo</span><select name="type">@foreach (\App\Models\Prospect::ACTIVITY_TYPES as $key => $label)@if ($key !== 'stage_change')<option value="{{ $key }}">{{ $label }}</option>@endif @endforeach</select></label><label><span>Fecha</span><input type="datetime-local" name="happened_at" value="{{ old('happened_at', now()->format('Y-m-d\TH:i')) }}" required></label><label><span>Resumen interno</span><textarea name="summary" rows="4" required>{{ old('summary') }}</textarea>@error('summary')<em>{{ $message }}</em>@enderror</label><label><span>Próxima acción</span><input name="next_action" value="{{ old('next_action') }}" placeholder="Ej. confirmar horario"></label><label><span>Fecha de próxima acción</span><input type="datetime-local" name="next_action_at" value="{{ old('next_action_at') }}"></label><button class="admin-button" type="submit">Agregar a la línea de tiempo</button><small>Estas notas son internas y nunca se muestran al cliente.</small></form>
        <section class="message-suggestions"><h2>Textos editables</h2><strong>Primer contacto</strong><p>Hola {{ $prospect->name ?: $prospect->business }}, soy de Sentriq. Gracias por contactarnos. Para orientarte mejor sobre {{ config('sentriq.services.'.$prospect->service_interest.'.name', 'tu proyecto') }}, ¿podemos confirmar la ubicación y lo que deseas proteger o automatizar?</p><strong>Seguimiento</strong><p>Hola {{ $prospect->name ?: $prospect->business }}, retomo tu solicitud con Sentriq. ¿Te parece bien que definamos el siguiente paso para tu proyecto?</p></section>
        <section class="linked-quotes"><h2>Presupuestos</h2>@forelse ($prospect->quotes as $quote)<a href="{{ route('admin.quotes.edit', $quote) }}">{{ $quote->number }} · {{ $quote->quote_date->format('d/m/Y') }}</a>@empty<p>No hay presupuestos vinculados.</p>@endforelse<a class="admin-button admin-button--secondary" href="{{ route('admin.quotes.create', ['prospect_id' => $prospect->id]) }}">Crear presupuesto</a></section>
    </aside></div>
@endsection
